spatie/laravel-backup

- composer.json
- src/Assets/config/laravel-backup.php
- src/Commands/BackupCommand.php
- src/Commands/BaseCommand.php
- src/Console.php
- src/DatabaseBackupServiceProvider.php
- src/DatabaseBuilder.php
- src/Databases/DatabaseInterface.php
- src/Databases/MySQLDatabase.php
Database dumper for Laravel 5, works only for mySQL databases.
Command is php artisan db:backup
> DB dumper for Laravel 5, only for mySQL db's

- src/DatabaseBackupServiceProvider.php
- stubs/gitignore.txt
Add writing a .gitignore file to the configured folder where the dump-files are stored (default: storage/db-dumps).
> Add writing gitignore to configured dump folder

- README.md
Change from
``` bash
php artisan backup:start
```
to 
``` bash
php artisan backup:run
```
> Wrong backup command in Readme

- src/BackupHandlers/Database/Databases/MySQLDatabase.php
- tests/database/MySQLDatabaseTest.php
A client of mine had some issues with this package recently: 
when exporting the database only without any socket defined, the exported file had only one table.
> Fix issue when no socket is defined

- src/Commands/BackupCommand.php
By calling `getBackupDestinationFileName()` twice, the actual destination backup filename will be different than the one displaying when backup finish. Specifically in the 'second' digit.
> fix displaying different backup destination filename

- src/Commands/BackupCommand.php
When specifying a path in the config, dirname returns the name of the folder and makeDirectory ensures that this folder exists.
When the destination.path is empty, dirname returns a period "."
When makeDirectory is called with period as the directory name, AWS throws the exception.
A workaround is to skip the makeDirectory call when dirname returns a period.
Fixes #55.
> Allow to write directly into an S3 bucket

- src/Commands/OverviewCommand.php
I think "number of backups" is clearer as a header because "amount of backups" could imply volume, not quantity.
> Clarification of table headers

- src/BackupHandlers/Database/Databases/MySQLDatabase.php
- src/BackupHandlers/Database/Databases/PgSQLDatabase.php
Current situation:
```php
// In Config
'dump_command_path' => '' -> Works
'dump_command_path' => 'path_without_slash' -> Fails **
'dump_command_path' => 'path_with_/' -> Works
** sprintf('%smysqldump ...', $this->getDumpCommandPath());
=> path_without_slashmysqldump
```` 
My PR fix that:
```php
'dump_command_path' => '' -> Works
'dump_command_path' => 'path_without_slash' -> Works **
'dump_command_path' => 'path_with_/' -> Works
** sprintf('%smysqldump ...', $this->getDumpCommandPath());
=> path_without_slash/mysqldump
````
> Better command path handling

- src/BackupServiceProvider.php
- src/Commands/ListCommand.php
Add new list command: `php artisan backup:list`
> List all backups
> Add list command

- CHANGELOG.md
- src/Tasks/Backup/BackupJobFactory.php
In v2 you had the mysql.dump_command_path config variable, which was crucial for me.
I've added it in v3 too, but dump_command_path is now specified for each db in config/database.php, since you can now backup multiple databases and might want to define one for each db.
Tested and working for MySQL.
NOT TESTED but probably working for PostgreSql.
Cheers and keep up the good work!
> Custom dump_command_path

- config/laravel-backup.php
- src/Notifications/Senders/Pushover.php
I think one of Pushovers best features is its different notification sounds.
With this change I made sure it wont break anybody's existing implementation if they don`t have the new config settings
```php
'sounds' => [
'success' => env('PUSHOVER_SOUND_SUCCESS','pushover'),
'error' => env('PUSHOVER_SOUND_ERROR','siren'),
],
```
`Line #59` @ `src/Notifications/Senders/Pushover.php` Makes sure they wont break
> Added the ability to change the pushover notification sounds

- src/Notifications/Senders/Pushover.php
Whenever I manually execute `php artisan backup:run --only-db` CURL will output the response data when it sends a notification to Pushover.
`{"status":1,"request":"f37d781ad8db193852e660394254731f"}`
Before this change my output looks like this
```bash
Starting backup...
Dumping database testproject...
Determining files to backup...
Zipping 0 files...
Copying 2016-04-02-130218.zip (size: 15.25 MB) to disk named backups-local...
Successfully copied .zip file to disk named backups-local.
{"status":1,"request":"f37d781ad8db193852e660394254731f"}Copying 2016-04-02-130218.zip (size: 15.25 MB) to disk named backups-s3...
Successfully copied .zip file to disk named backups-s3.
{"status":1,"request":"67be53532fff0515ae5b3a57d0a6695d"}Backup completed!
```
With this change my output is much …
> Remove unnecessary output from curl when using pushover

- config/laravel-backup.php
- src/Tasks/Backup/FileSelection.php
- tests/Unit/FileSelectionTest.php
You can use a wildcard (*) in the include and exclude paths.
This is really useful in combination with https://github.com/spatie/laravel-medialibrary
Using a wildcard you're able to skip the backup of all the converted media. This will save a lot of backup storage in large projects.
example:
``` base_path('public/media/*/conversions') ```
> Added support for wildcards in the paths

- config/laravel-backup.php
- src/Tasks/Backup/BackupJobFactory.php
- src/Tasks/Backup/FileSelection.php
FileSelection now follows symlinks. This is useful if you use a deployment tool like [Capistrano](http://capistranorb.com/documentation/getting-started/structure/).
> follow links

- src/Tasks/Backup/BackupJob.php
- src/Tasks/Backup/FileSelection.php
- tests/Unit/FileSelectionTest.php
Currently the `FileSelection` class lists all files that are excluded, and filters them out of the included file list. This implementation doesn't list all the excluded files, but just checks the paths with `starts_with`.
This should greatly improve speed since file IO is expensive, and in turn reduce memory usage.
Bonus: `FileSelection` has been refactored to pass around collections instead of arrays, cleaning up the code a bit.
> Better FileSelection

- src/Commands/BackupCommand.php
- src/Tasks/Backup/BackupJob.php
Allow set set the filename via `php artisan backup:run --filename=db.zip`
Fixes #188
> Make backup filename configurable

- .travis.yml
This will cache the composer downloads as zip, which makes the tests run faster.
Also added 7.1 to the matrix.
> Cache composer, test on 7.1

- src/BackupDestination/BackupDestination.php
- src/Tasks/Backup/BackupJob.php
Unnecessary listing of files as the write() method also throws an error when not reachable.
Fixes #188
> Remove isReachable() check

- src/Tasks/Backup/DbDumperFactory.php
- tests/Unit/DbDumperFactoryTest.php
This PR fixes issue #163 
If a read database host is available, this will be used.
Otherwise, it will fall back to the default host key.
> Use read database connection if available

- src/Notifications/BaseNotification.php
Some slack-like tools (like mattermost) don't parse json as cleanly as slack does.
> Updated BaseNotification to return all values as string.

- composer.json
Version constraints for `spatie/temporary-directory` was set to `~1.0.0`, which prevented composer from resolving the latest release of the package. Setting it to `~1.0` allows to depends on any `1.x`version. 
Fix  https://github.com/spatie/laravel-backup/issues/358
> Fix version  constraints for package spatie/temporary-directory

- src/Tasks/Monitor/BackupDestinationStatus.php
As described in https://github.com/spatie/laravel-backup/issues/351#issuecomment-277183330 this PR forces the return type of `BackupDestinationStatus::maximumAllowedUsageInBytes()` to be an integer, even on platforms (armv7l) where it might be converted to a float.
> Force BackupDestinationStatus::maximumAllowedUsageInBytes() to return an integer

- src/Tasks/Backup/Zip.php
> Trim starting `/` from filepath in backup archive to avoid empty root directory

- composer.json
I noticed an issue regarding the `exclude` array while running Laravel 5.4 with PHP < 7. The folders listed in the `exclude` array aren't excluded. This results in massively increasing backup files. The problem is described in #378 as well.
So I updated the `composer.json` in v3 to be compatible with Laravel 5.4 too.
My backups worked fine afterwards. The `exclude` folders are excluded as desired. ;)
> Updated composer.json v3 to be compatible Laravel 5.4 as well

- README.md
Using badge-poser and packagist to show the latest stable version instead of the latest release in `README.md`. So the v3 releases won't be in the badge event if they are newer than a v4 release.
> Using badge-poser

- src/Notifications/BaseNotification.php
Adding backupName to backupDestinationProperties makes the overview more clear when monitoring multiple backups.
> Added backupName to backupDestinationProperties

- src/Notifications/BaseNotification.php
If an array with an empty string `[""]` or simply an empty string `""` is used as the notification channel we'll default it to an empty array `[]` so Laravel doesn't get confused and starts sending mails.
This should fix #355
> Check for empty string in notifications config

- CHANGELOG.md
- src/Tasks/Backup/DbDumperFactory.php
The `setDefaultCharacterSet` method will be used for `MySql` dumper instances to set the charset to the configured value in `database.php`.
Fixes #411
> Use configured charset when dumping database

- src/BackupDestination/BackupCollection.php
- src/BackupDestination/BackupDestination.php
- src/Tasks/Monitor/BackupDestinationStatus.php
I noticed running `backup:list` with 2 backups on a disk generated about 90 filesystem API requests.
This PR caches the `BackupCollection` and the `BackupCollection` size when running the `backup:list` command and brings that number down to 20 API requests.
(still not ideal but this could be further improved by using [memory caching](https://flysystem.thephpleague.com/caching/) when the adapter is registered in the application)
> Optimise backup:list for external file systems

- config/laravel-backup.php
- src/Tasks/Backup/BackupJob.php
- src/Tasks/Backup/Gzip.php
- tests/Unit/GzipTest.php
According to issue #372, add an option to gzip the SQL files before zipping them. Very useful in my use case since .sql.gz files are a lot smaller while still able to be loaded into my SQL client, unlike .zip files.
> Add feature to optionally gzip dumped .sql

- src/Commands/ListCommand.php
Call to undefined method Spatie\Backup\Tasks\Monitor\BackupDestinationStatus::getFilesystemName()
> Call to undefined method getFilesystemName()

- src/Tasks/Backup/BackupJob.php
- tests/Integration/BackupCommandTest.php
- tests/Integration/TestCase.php
This fixes #439
Appends the database type to the file name to prevent multiple databases with the same name from being overwritten during backup.
> Updated database dump file name generation to prevent overwrite.

- README.md
The current link is to the list of laravel packages
> Corrects link to the postcard page in README

- tests/Unit/FileSelectionTest.php
Selection of files ($fileSelection->selectedFiles())  seems that in some environments generates an unordered array giving a false positive #500 . Sort the arrays before compare it fixes the problem.
> Fix test failure

- src/Tasks/Backup/BackupJob.php
- tests/Integration/BackupCommandTest.php
There is an edge case where the temp file fills up until it is using all available space, causing future backups to fail. Since a failed backup does not clean the temp directory, the backup process will never succeed without intervention.
This is solved by always clearing the temp file before starting the backup job.
> Empty the Temp directory before starting a backup job

- src/Notifications/Notifications/CleanupHasFailed.php
fix the :application_name not getting translated for failed backup cleanup notifications
> fix CleanupHasFailed application_name translation not working

- README.md
I noticed the link to v4 in the "Using an older version..." section was actually pointed to v3, so I took a moment to correct it
> correct link to v4 in README.md

- src/Tasks/Cleanup/Strategies/DefaultStrategy.php
- tests/Integration/CleanupCommandTest.php
This PR fixes a bug in `DefaultStrategy` where all backups would be removed when cleaning old backups due to maximum storage being reached (see #505).
This PR also fixes the `it_can_remove_old_backups_until_using_less_than_maximum_storage` test to catch the issue if it were to happen again.
Finally the testing `APP_NAME` environment variable is set to `mysite` in `phpunit.xml.dist` however in a lot of the tests `mysite.com` was used. I've made all the tests use the same `APP_NAME` now for consistency.
Fixes #505
> Fix deleting all backups when using maximum storage

- tests/Integration/BackupDestination/BackupTest.php
Small one: use [`assertFileExists`](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertFileExists) and [`assertFileNotExists`](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertFileExists).
> Use assertFileExists and assertFileNotExists

- src/Commands/BackupCommand.php
- src/Commands/CleanupCommand.php
I'm using this package as part of a deployment hook on Envoyer so that I can backup my site every time I deploy.
Currently, if a backup fails, the deployment script carries on because the `backup:run` command returns an exit code of `-1`.
I've updated it in this PR so that it return `1` instead which signals a general error and will fail the deployment if a backup cannot be taken successfully.
> Use correct exit codes

- src/Tasks/Backup/BackupJob.php
- src/Tasks/Cleanup/CleanupJob.php
- tests/Integration/BackupCommandTest.php
This PR contains a couple of things:
If a Backup or Cleanup task fails, it will re-throw the caught exception, to allow the calling Command to catch the exception again and act accordingly (in this case, returning the correct exit code).
This shouldn't cause any regressions - I've been careful to delete the temporary directory before re-throwing the exception in the `BackupJob` class. The notifications should also still get sent, and the console output should remain the same.
The `run()` methods of both the `BackupJob` and `CleanupJob` are only called in the Commands, and both of these have extra `try..catch` blocks around them to catch the re-thrown exception.
I've also fixed the two failing tests that weren't updated in #606. Sorry... That was my mistake 😄
> Rethrow exceptions to exit properly on error

- src/Tasks/Backup/BackupJob.php
Like described in #662. This will cleanup disk space when possible before creating zip.
> #662 - Remove the dumped database file after gzipping it

- composer.json
- src/Tasks/Backup/BackupJob.php
I didn't update the changelog because I wasn't sure to update if the update would be a minor or major improvement. The doubt was because the composer.json file has been changed too, because it uses functionality that wasn't available in a version from db-dumber before the one specified.
> Database dump is streamed to gzip now, saves a lot of space.

- src/BackupDestination/BackupCollection.php
- src/BackupDestination/BackupPath.php
- tests/Integration/BackupDestination/BackupCollectionTest.php
This PR compliments #646 with a test `it_checks_mime_type_instead_of_extension`, however it also addresses an issue introduced with that PR.
After updating to the latest `spatie/laravel-backup` version, my BackBlaze disk was showing 0 backups suddenly. I discovered that [the backblaze adapter returns `false`](https://github.com/mhetreramesh/flysystem-backblaze/blob/master/src/BackblazeAdapter.php#L179-L182) for mime types. This is the [valid return value for an error](https://github.com/thephpleague/flysystem/blob/de8b364f4aada1ecfdc03c55c35bf2f42d402fc9/src/FilesystemInterface.php#L79). Looking through a [few](https://github.com/nikkiii/flysystem-acd/blob/master/src/AmazonCloudDrive.php#L324) [other](https://github.com/nao-pon/flysystem-google-drive/blob/master/src/GoogleDriveAdapter.php# …
> Check false mime types + tests

- composer.json
Since the last version, php 7.0 is no longer supported. This PR fix composer.json to prevent php 7.0 apps to DL a non compatible version.
> Require php 7.1

- config/backup.php
It took me a while to figure out how to exclude a table from the dump-file, so I added a short instruction on how to customize the dump content.
I'm not sure if this is the right place to add it, or if it's the right level of detail, but I think it needs to be mentioned somewhere. Might be worth mentioning on the documentation page as well.
> Add instructions on how to customize the content of database dumps.

- composer.json
- config/backup.php
- src/Tasks/Backup/BackupJob.php
- tests/Integration/BackupCommandTest.php
Adding bzip2 to Laravel-Backup.
> bzip2 creates about 15% smaller files than gzip. bzip2 compresses somewhat slower than gzip, but seems that it hasn't prevented bzip2 from getting popular. 
For quote's source [here](https://tukaani.org/lzma/benchmarks.html)
Edit: bzip2 can be imported with [Sequel Pro](https://sequelpro.com/) as with gzip
> Add bzip2 compress option

- src/BackupDestination/BackupDestination.php
- src/Tasks/Cleanup/CleanupJob.php
when running the `artisan backup:clean` command a wrong backup size is
shown due to caching. Fixes #776
> clear the backup-size cache (fixes #776)

- src/Notifications/BaseNotification.php
- tests/Integration/CleanupCommandTest.php
- tests/TestHelper.php
This pull request implements a fix for issue #746 and possibly #505.
I believe the issue is related to cached backup destinations -- if all the backup files were to be deleted, expect for the latest, and the `CleanupWasSuccessful` event were to be fired, then an exception would be thrown. This was being caused in the [BaseNotification at line 52](https://github.com/spatie/laravel-backup/blob/master/src/Notifications/BaseNotification.php#L52) when it was trying to grab the `newestBackup` size because it was using cached values.
I have also added a test which will fail if you remove the `$backupDestination->fresh();` introduced in `BaseNotification` within this PR.
> Clear cache before attempting to send notification

- src/BackupDestination/BackupDestination.php
- tests/Integration/BackupDestination/BackupTest.php
Add optionally params for S3-compability storages. 
For usage you should set at config/filesystems.php for your backup disk array options 'dump_extra_options', for example:
```
's3-backup' => [
'driver' => 's3',
...,
'backup_extra_options' => [
'StorageClass' => 'COLD'
]
],
```
> add extra options to backup destination at writeStream

- resources/lang/nl/notifications.php
Hey all, I noticed a Dutch translation was missing since my app uses the `nl` locale, so I created one. Some notes on the translation as I am not a professional translator;
- I've used the term 'niet gezond' rather than 'ongezond' for unhealthy as I felt the latter could be more easily read as 'gezond' while skimming through the notifications. I'm sure there is a better way of phrasing it though.
- The grammatically correct translation for 'backup destination' is 'back-upbestemming' and I'm currently using that, but it's not very comfortable to read.
- I've mostly translated the English sentences 1:1 including the sentence structures, so there could be some anglicism in there.
It's more than a decent enough translation for its use case, but feel free to improve on it.
> Added Dutch translation

- config/backup.php
In v6.0 the config value of `backup.name` changed from `config('app.name')` to `env('APP_NAME')`.
This PR makes the same change to  the `monitor_backups.name` config value.
> Updates monitor_backups.name config value

- resources/lang/en/notifications.php
Fix typo in the word "backup" when sending failed English notifications to make consistent with other spellings of the word. The consistent language may help those leveraging email filtering rules to perform actions, such as auto-forwarding and filing messages.
> Fix typo in english backup notification

- src/Tasks/Backup/BackupJob.php
- tests/Commands/BackupCommandTest.php
laravel-backup always names the dump file 'sqlite-database.sql' for sqlite.
Therefore, if you have multiple SQLite databases, only one database is backed up and the other databases are not backed up.
This patch adds the connection name before "database" and backs up all databases.
(This PR is same as #892. target to v6.)
> fix bug multiple sqlite dump-file is same name. (v6)

- src/Tasks/Backup/DbDumperFactory.php
- tests/DbDumperFactoryTest.php
This feature adds a way to add custom database dumpers. In my case this is useful, because we are dealing with a docker container and we cannot rely on the mysql dump command outside that container (different mysql versions unfortunately). 
You can either add dumpers for custom connections:
```
DbDumperFactory::extend('some_other_connection', function() {
return new YourCustomDumper();
});
```
Or override an existing dumper:
```
DbDumperFactory::extend('mysql', function() {
return new YourCustomMysqlDumper();
});
```
Relevant docs update: https://github.com/spatie/docs.spatie.be/pull/411
> Add support to add custom dumpers to DbDumperFactory

- config/backup.php
- docs/installation-and-setup.md
I was looking on how to implement this option myself, as I backup DB's that are ~3GB in size, and with locking the tables it takes a while before they're available again.
> Add example on how to use useSingleTransaction to avoid locking DB's

- src/BackupDestination/Backup.php
Hi, I whipped this up quickly after running into S3 rate limit issues (see also #783 #618)
The number of calls made to the storage backend seemed a bit high to me, and by caching these properties I managed to reduce them 4-fold.
I hope this is an acceptable patch to you. Of course caching these properties makes you prone to some invalid states such as running deletes outside the knowledge of the `Backup` file, but as far as I can see this is currently not happening.
> Prevent excessive IO calls by caching Backup properties

- docs/installation-and-setup.md
It erroneously referred to the v5 version
> Fix link to current version of documentation

- src/Tasks/Backup/BackupJob.php
This ensures backups continue even if there is a notification failure (#960) and dumps the error to console. 
It doesn't distinguish which notification failed though. Not sure if that is an issue.
Hope this helps. Thank you for a great package!
> Fix backup stopping on notification failure (#960)

- config/backup.php
- src/BackupServiceProvider.php
I've a custom laravel folder structure and there is no way on how to customize the published files (translations) destination.
As mentioned in the title, this PR adds this feature.
> [Feature] Allowing to customize the destination path when publishing the translations

- src/BackupDestination/Backup.php
- src/Tasks/Cleanup/Strategies/DefaultStrategy.php
- tests/BackupDestination/BackupTest.php
This PR allows you to read `disk()` on `Backup` which helps when writing your own `CleanupStrategy`
```php
class MyCleanupStrategy extends DefaultStrategy
{
public function deleteOldBackups(BackupCollection $backups)
{
// backups can only be from one disk per call, but all go through this function
[$s3Backups, $dropboxBackups] = $backups->partition(
function (Backup $backup) {
return $backup->disk() === 's3';
}
);
// s3 backups follow the DefaultStrategy
parent::deleteOldBackups($s3Backups);
// only keep the latest Dropbox backup
$dropboxBackups->shift();
$dropboxBackups->each->delete();
}
}
```
> Add disk getter function on Backup

- src/BackupDestination/Backup.php
- src/BackupDestination/BackupCollection.php
- src/BackupDestination/BackupDestination.php
- src/Helpers/Format.php
- src/Tasks/Backup/Zip.php
- src/Tasks/Monitor/HealthChecks/MaximumStorageInMegabytes.php
- tests/BackupDestination/BackupCollectionTest.php
- tests/BackupDestination/BackupTest.php
Tested these changes on my system and it worked with a 32bit php system. The notification and the backup:list command is working again with no failure.
It should be tested on a 64bit php system before!
> php 32 bit compatibility

- composer.json
- src/Tasks/Backup/DbDumperFactory.php
- tests/DbDumperFactoryTest.php
Added ability to handle database urls for database connections introduced in [Laravel v5.8.15](https://github.com/laravel/framework/blob/master/CHANGELOG-5.8.md#v5815-2019-04-27)
Tests are provided.
> Handle database urls for database connections

- src/Commands/MonitorCommand.php
I would like to use Gitlab scheduled pipelines to monitor my application backups, but `php artisan backup:monitor` returns 0 whatever the result. With my suggestion, my pipeline will fail as excpected.
> Monitor command should fail in CI if backups are considered unhealthy

- src/Commands/MonitorCommand.php
- tests/Events/UnhealthyBackupWasFoundTest.php
- tests/HealthChecks/IsReachableTest.php
- tests/HealthChecks/MaximumAgeInDaysTest.php
- tests/HealthChecks/MaximumStorageInMegabytesTest.php
There was an error in my last pull request, `return 1` was in the `each` function so command was always returning 0.
I refactored the function ans I TESTED IT in a CI environment.
Sorry for wasting your time.
> Fix non zero error code in monitoring command

- src/Exceptions/NotificationCouldNotBeSent.php
- src/Notifications/EventHandler.php
```diff
-    public static function noNotifcationClassForEvent($event): self
+    public static function noNotificationClassForEvent($event): self
```
> Corrects a typo in the method name

- docs/requirements.md
According to [composer.json](https://github.com/spatie/laravel-backup/blob/master/composer.json) it should be PHP 7.2
> Fix doc requirements

- src/Tasks/Backup/DbDumperFactory.php
When using a custom connection name the MongoDB does not use the authentication database due to a hardcoded reference
> MongoDB authentication uses correct connection name

- src/Commands/BackupCommand.php
Added the timeout parameter to set the maximum execution time, this could be useful if the amount of data to backup is big.
> Added support to set execution timeout

- tests/Commands/BackupCommandTest.php
Hello,
This PR will fix : 
- 1 typo in `tests/Commands/BackupCommandTest.php`
Cheers! :robot:
> Fix typo in tests/Commands/BackupCommandTest.php

- config/backup.php
- src/Tasks/Backup/BackupJobFactory.php
- src/Tasks/Backup/FileSelection.php
I tried to respect the architecture and documentation, let me know if something does not respect the way of thinking of this package.
You can set `backup.source.files.ignore_unreadable_directories` in the config file.
If true, it will ignore the folders it doesn't have permission to access.
Otherwise, it will act normal and raise an error.
> Avoid Unreadable folders errors, can be set from config

- src/BackupDestination/Backup.php
- src/Tasks/Backup/BackupJob.php
Implemented two improvements
- get lastmod date of backup from the filename. If that fails, ask the remote FS
- manually keep track of `exists` status
There's more room for improvement:
- use bulk deletes instead of one delete at the time
- get size and date metadata in bulk
But these require significant refactors.
Fixes #1067 and probably relates to #1059
> Reduce number of filesystem calls for Backup `exists` and `date`

- README.md
By the way: wouldn't it be better to introduce a bump in the required PHP version as a major release? Was quite surprised that upgrading from 6.11.1 to 6.11.2 stopped working with PHP 7.2 suddenly.
> Update required PHP version from 7.2 to 7.3 in Readme

- src/Tasks/Cleanup/CleanupJob.php
- src/Tasks/Cleanup/CleanupStrategy.php
My application backs up to two disks — local storage, and an S3 bucket. I want to keep just 7 days of backups locally, but a years' worth on S3.
I wrote a custom `CleanupStrategy` class, and set it as the strategy in the backup config file. I was intending to handle the logic for each disk in this custom class, but then realised the `CleanupJob` task only passes a `BackupCollection` to the strategy, with no (easy) way to determine where those backups are located.
This PR simply sets a `backupDestination` property on the abstract `CleanupStrategy` class, allowing custom strategies that extend this class to identify the intended backup destination and react accordingly.
This should be backwards-compatible with any classes implementing the abstract `CleanupStrategy` class.
Thanks for …
> Allow a CleanupStrategy to access its intended BackupDestination

- README.md
- config/backup.php
- docs/high-level-overview.md
- docs/installation-and-setup.md
- docs/introduction.md
- docs/requirements.md
- docs/sending-notifications/customizing-the-notifiable.md
- docs/sending-notifications/overview.md
- Update information about minimal required version of PHP and Laravel
- Update links to Laravel documentation to point to latest version
- Sending Slack notifications requires `laravel/slack-notification-channel`, which requires (in `composer.json`) `guzzlehttp/guzzle`. Comment in config file instructed to require both of them, and documentation didn't event mention `laravel/slack-notification-channel`. Fixed that!
> Update README.md, docs and comment in config file

- config/backup.php
- docs/installation-and-setup.md
- docs/taking-backups/overview.md
- src/Tasks/Backup/Zip.php
- tests/Commands/BackupCommandTest.php
As mentioned here: https://github.com/spatie/laravel-backup/issues/132#issuecomment-219143235
And here: https://github.com/spatie/laravel-backup/issues/1065
This pull request adds an option to enter a relative path that is removed from the full path of the files in the resulting ZIP-file.
> add option to add files to zip-file using relative path

- src/BackupDestination/BackupDestination.php
- src/Exceptions/InvalidBackupDestination.php
Issue: #1126
This pull request is to show Backup destination hiding important error messages.
> Fix to show Backup destination hiding important error message

- config/backup.php
- docs/advanced-usage/binary-database-dumps-with-postgresql.md
- docs/installation-and-setup.md
- src/Tasks/Backup/BackupJob.php
- tests/Commands/BackupCommandTest.php
As per the discussion: https://github.com/spatie/laravel-backup/discussions/1204
This PR allows renaming the database dump file extension. as well as updating the documentation and a test. I've also added a documentation section about generating binary dumps with `pg_dump` that this feature is useful for.
Thanks!
> File extension override

- src/BackupDestination/BackupDestination.php
Protected $this->disk->allFiles() call with try catch block 
This fixes #1225
> Fixed notification failure on unreachable disk

- composer.json
This PR updates the `spatie/temporary-directory` package to v2.0.0, which is the latest version of the package as of this PR submission.
> Update spatie/temporary-directory package to latest version

- src/Events/DumpingDatabase.php
- src/Tasks/Backup/BackupJob.php
- tests/Events/DumpingDatabaseTest.php
With this event you can customize the `DbDumper` options like `skipLockTables`, `useSingleTransaction`, etc.
(I intentionally didn't use constructor property promotion hoping that if you decide to merge it, it could also be merged into v6.)
> Add DumpingDatabase event

- src/Commands/BaseCommand.php
PR for #1288 
Checks `PHP_OS_FAMILY` constant for "Windows" and avoids registering `SIGINT`.
Tested on Windows 10 and Fedora 33
> Avoid SIGINT on Windows

- src/Commands/BaseCommand.php
this is to fix issue #1309 when executing command from the web instead of CLI
> Fix issue #1309

- src/BackupDestination/BackupDestination.php
- src/Exceptions/InvalidBackupDestination.php
Fixes #1326 
This is an important change, as currently laravel-backup reports all misconfigured S3 backups as successful!
This change only applies to laravel-backup v6, which uses flysystem v1 (laravel-backup v7 uses flysystem v2 which has a different interface).
> Detect write failures

- composer.json
- src/Commands/BackupCommand.php
- src/Commands/BaseCommand.php
- src/Tasks/Backup/BackupJob.php
Use signals only when ext-pcntl is available
It's a workaround after [Simfony/Console 681a074](https://github.com/symfony/console/commit/681a074054bc6fc00dfeb5f862f266847d9a8465), it is gonna be on the next release, This PR allows avoid signals on windows and linux without ext-pcntl, so dependency can be removed
> Support when no signal's extension

- src/BackupDestination/Backup.php
- src/BackupDestination/BackupDestination.php
- src/Exceptions/InvalidBackupFile.php
- tests/BackupDestination/BackupTest.php
fix #1326 
I have done research on this and I would like to note it here.
league/flysystem - v1: Methods in League\Flysystem\FilesystemInterface doesn't throw exceptions instead returns true, false, resource, array. In flysystem v2 there are [exceptions which will be thrown](https://flysystem.thephpleague.com/v2/docs/usage/exception-handling/) instead of returning false.
In this package only Backup@delete checks for its result for rest of the methods(writeStream, readStream) I've added checking the result and throwing exception.
Even though I tried to add tests for these cases, I find it difficult to achieve
> adds: exception to throw when flysystem returns false

- .github/workflows/run-tests.yml
- src/Tasks/Backup/BackupJob.php
- src/Tasks/Backup/FileSelection.php
- src/Tasks/Backup/Zip.php
- tests/Commands/BackupCommandTest.php
- tests/FileSelectionTest.php
- tests/TestCase.php
- tests/stubs/.dot/file1.txt
- tests/stubs/file
- tests/stubs/file1.txt.txt
For V6
Closes #1357
Closes #1312
Closes #1298
```
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.5
Configuration: /var/www/github/laravel-backup/phpunit.xml.dist
...............................................................  63 / 108 ( 58%)
.............................................                   108 / 108 (100%)
Time: 00:29.707, Memory: 38.00 MB
OK (108 tests, 2267 assertions)
```
@freekmurze  Maybe just merge this and close other PRs, so it can be merged to V7 for upgrade
> [V6] Fix bugs

- CHANGELOG.md
We were wondering about the undocumented renaming of notification classes. It is a breaking change, so we would suggest to add this important information to the changelog at least.
> Add missing notification renaming to the changelog (7.0.0)

- src/Tasks/Backup/Zip.php
Avoid full path on db dumps
Revert bug added on #1365 (Sorry, my mistake)
Closes #1377
> [v7] **Important** Avoid full path on db dumps

- config/backup.php
We are using custom notifications and renamed the class names to the event names (like described in config).
We noticed that you need to suffix the class name with `Notification`.
See: https://github.com/spatie/laravel-backup/blob/main/src/Notifications/EventHandler.php#L43-L47
So in conclusion the class name should match the original [notification class names](https://github.com/spatie/laravel-backup/tree/main/src/Notifications/Notifications) ones.
F.e. 
class_basename(`Spatie\Backup\Events\BackupHasFailed`) +  `Notification` = `BackupHasFailedNotification`
This PR changes the doc-block in the config.
> Update notification doc-block in backup.php

- src/Tasks/Backup/Zip.php
Avoid full path on db dumps
Revert bug added on #1366 (Sorry, my mistake)
Closes #1377
Put `db-dump` directory at the top level
> [v6] **Important** Avoid full path on db dumps

- composer.json
Laravel 9 only supports league/flysystem v3, so offering v2 in the composer file is unnecessary as it can never be installed.
> Drop offered flysystem version that is uninstallable

- src/Commands/ListCommand.php
- src/Commands/MonitorCommand.php
- tests/Commands/ListCommandTest.php
- tests/Commands/MonitorCommandTest.php
Related to PR #1494 
Since that approach won't work as mentioned in my [comment ](https://github.com/spatie/laravel-backup/pull/1494#issuecomment-1055326350), this approach warns the user instead to ensure that his config key uses the snake_case format instead of camelCase.
> Warns the user about old-style config files for backup:list and backup:monitor commands

- src/BackupDestination/BackupDestination.php
The `allFiles()` method is recursive, and given that `isReachable` just tests if the destination is available and does not use the result of the method call, it seems unecessary to fetch recursively.
This PR swaps to the non-recursive `files()` method to do less work to determine the same answer.
> Use non-recursive files() method to test if destination is reachable

- config/backup.php
Using `null` as the defaults didn't work when just entering the webhook URL. Most of the time, you will make a webhook for each notification and set name/avatar there.
This is with it being `null`:
```
Spatie\Backup\Notifications\Channels\Discord\DiscordMessage::from(): Argument #1 ($username) must be of type string, null given
```
> Use empty string for Discord defaults

- src/Commands/MonitorCommand.php
The output messages for this command are missing the name of the backup. This PR proposes to fix that. So instead of getting output like this:
```
The backups on s3 are considered healthy.
The backups on s3 are considered healthy.
The backups on r2 are considered healthy.
The backups on r2 are considered healthy.
```
You would instead get this:
```
The Project One backups on the s3 disk are considered healthy.
The Project Two backups on the s3 disk are considered healthy.
The Project Three backups on the r2 disk are considered healthy.
The Project Four backups on the r2 disk are considered healthy.
```
> Improve output messages for backup:monitor command

- .github/workflows/dependabot-auto-merge.yml
This PR adds dependabot automation for this repository.
This PR adds a dependabot configuration file that enables weekly update checks for all github actions used within workflows in the project (if it does not exist).
Additionally, it includes a workflow that automatically merges dependabot PRs for minor and patch version updates (major version bumps must be manually merged to avoid breaking changes, with one exception - see below).
Finally, Github Actions that have a major version update AND a compatibility score of >=90% are automatically merged as way to reduce the manual work of merging PRs that are of no risk of breaking changes. ONLY Github Actions that have a major version update are considered for automatic merging.  Other dependencies are excluded.
Using these features will help …
> Add Dependabot Automation

- src/Commands/BackupCommand.php
- src/Commands/CleanupCommand.php
- src/Commands/ListCommand.php
- src/Commands/MonitorCommand.php
This PR converts returning integer exit codes to returning the constants defined in [Symfony Commands class](https://github.com/symfony/console/blob/6.3/Command/Command.php?plain=1#L38), making the code more expressive and easier to understand.
```php
class MyCommand extends Command
{
public function handle(): int 
{
// do something that fails...
return 1;
}
}
```
```php
class MyCommand extends Command 
{
public function handle(): int 
{
// do something that fails...
return static::FAILURE;
}
}
```
- Return success exit code where command is returning failure or void, ensuring the `handle` methods always returns an integer, never void.
- Declare return type `int` on `handle` methods.
If the user is extending one of the commands the package provides and are overriding the `handle` method …
> Return `Command` constants instead of integers in commands

- src/Commands/BackupCommand.php
- src/Events/BackupHasFailed.php
- src/Exceptions/BackupFailed.php
- src/Tasks/Backup/BackupJob.php
- tests/Notifications/EventHandlerTest.php
Fixes #1662
This PR addresses an issue with exception handling in [BackupJob](https://github.com/spatie/laravel-backup/blob/f4a2abc673ed61447ca748d02e9cc8be16e1c485/src/Tasks/Backup/BackupJob.php#L172C13-L172C13). 
As both the `BackupCommand` command and `BackupJob` are handling exceptions the result is both send the failure notification when they deem the process to have failed.
With these changes `BackupCommand` will exclusively handle notifying the user if a failure scenario occurs. Due to the command being able to retry itself it makes the most sense to allow **it** to determine when it considers the process to have failed. 
--------
Before these changes the `copyToBackupDestinations` method of `BackupJob` would fire the backup failed event and pass the destination as a parameter. …
> Send one notification on backup failure

- src/BackupServiceProvider.php
As it is, events aren't properly registered. If you run `artisan event:list` the events won't show. But moving to booted instead, will register the events correctly.
> Move registering events to "booted" rather than "registered"

- config/backup.php
- src/Tasks/Backup/BackupJob.php
- tests/Commands/BackupCommandTest.php
At this moment, after unzipping several dumps, the db filename always is the same - which makes it difficult to do any comparisons between them, and we are unaware when they have been taken.
With this PR, you can choose a timestamp format (through the `'database_dump_file_timestamp_format'` config option), which will be inserted into the db dump filename and now it's clear when it was taken, eg.:
`mysql-PROJECT-2023-10-02-07-00-00.sql`
> Possibility of adding timestamp to database dump filename

- CHANGELOG.md
- config/backup.php
- src/Tasks/Backup/Zip.php
- tests/Commands/BackupCommandTest.php
This PR adds possibility of choosing zip compression method and its level through these config options:
- `['destination']['compression_method']`
- `['destination']['compression_level']`
Now it's possible to select the specific compression method like `ZipArchive::CM_DEFLATE` or `ZipArchive::CM_XZ` or not use compression at all with `ZipArchive::CM_STORE`. 
It's possible to experiment and choose optimal compression for one's needs, which impacts memory/cpu usage plus time consumption and finally file size. 
In case of using only db dumps, I have decided to directly compress .sql with `GzipCompressor::class` and not compress .zip archive, which gives me less CPU usage and still acceptable file size.
> Possibility of choosing zip compression method

- config/backup.php
When reading the config the first time, I was very confused about the term "daily/weekly/monthly/yearly backup". 
The confusion arises because the terms imply a specific backup frequency but in reality, the package uses these terms to describe how long backups should be retained in each category, regardless of the actual frequency at which backups are created.
For better clarity, I would recommend to update the comments as proposed.
> Improve strategy comments

- docs/advanced-usage/isolated-mode.md
- src/Commands/BackupCommand.php
- src/Commands/CleanupCommand.php
- src/Commands/MonitorCommand.php
I updated the `backup`, `clean` and `monitor` commands so that they can be run in isolated mode.
See https://github.com/spatie/laravel-backup/discussions/1750 for the reasoning behind this.
> Made it possible to run the backup, cleanup and monitor commands in isolated mode

- resources/lang/pt/notifications.php
This PR resolves an issue with duplicated Portuguese translation keys for backup date. The keys for `newest_backup_date` and `oldest_backup_date` were previously mapped to incorrect values related to backup size. 
This update ensures each key has a unique and correct translation, preventing `backupDestinationProperties()` from overwriting dates with sizes in notifications.
> Fix duplicate Portuguese translations for backup dates

- config/backup.php
- docs/cleaning-up-old-backups/overview.md
- docs/installation-and-setup.md
- src/Tasks/Cleanup/Strategies/DefaultStrategy.php
Hi,
I've added unlimited storage option for backups. We had a situation where we wanted to keep our backups for 30 days (backup command is run every hour) and it's a fairly large databse which grows each day so it's a little hard to determine max limit for storage and it feels kinda wrong to set it to some very very big number.
Thx!
> Added null option for unlimited backup storage size

- config/backup.php
- docs/installation-and-setup.md
- src/Tasks/Backup/BackupJob.php
- tests/Commands/BackupCommandTest.php
_Code and tests are added. Documentation update was omitted because a similar config ```database_dump_file_timestamp_format``` is not documented. I'm happy to add documentation should that be required for a merge._
This PR adds a config option at ```config('backup.backup.database_dump_file_use_connection_name')``` of type boolean, defaulting to ```null``` and thus uses the database name as it always has.
This config, if set to true, uses the connection's key from ```config('database.connections')``` in the dump file name instead of the database name
**Use Case**
I have 2 connections defined to the same database, each with different db-dumper options. I have one to dump only the schema (see my PR to [spatie/db-dumper#208](https://github.com/spatie/db-dumper/pull/208)) and a second to dump …
> Add config option database_dump_file_use_connection_name

- docs/advanced-usage/backing-up-a-non-laravel-application.md
- docs/cleaning-up-old-backups/overview.md
- docs/monitoring-the-health-of-all-backups/overview.md
- docs/taking-backups/overview.md
The internal links in the documentation have been corrected to ensure accuracy. Previously, the links in the 'notifications', 'installation instructions', and 'installation and setup' sections went to "/laravel-backup/v8/..." but have now been updated to "/docs/laravel-backup/v8/..."
> Update documentation internal links

- src/Config/NotificationMailConfig.php
- tests/Notifications/EventHandlerTest.php
Fixes issue for 9.x revision described here: Send mail notifications to multiple addresses failed https://github.com/spatie/laravel-backup/issues/1291#issuecomment-2205283765
> [9.x] Add support for both single email string and array of email strings

- src/Notifications/Channels/Discord/DiscordMessage.php
Fixes #1815 
This PR fixes an issue caused by using an empty string for the Discord Webhook `username` property.
According to [Discord's documentation](https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params), the `username` field is optional and when set, requires it to be between 1 and 80 characters long. This lines up with the `name` field when [creating a webhook](https://discord.com/developers/docs/resources/webhook#create-webhook).
The current implementation of the notification doesn't follow that. If the `backup.notifications.discord.username` is an empty string (which is currently the default), the notification is never sent due to a validation error. See the mentioned issue above for details.
This PR fixes these issues by only setting the username …
> [9.x] Fix empty string in `backup.notifications.discord.username` to fail sending a notification

- resources/lang/es/notifications.php
Spanish language file has a double space in one of the translation strings.
> Fixing minor typo in Spanish language file.

- src/Notifications/Channels/Discord/DiscordMessage.php
Backport of #1821 for the v8 branch
See also #1818
> [8.x] Only add the username property if it's not empty

- src/Notifications/Channels/Discord/DiscordMessage.php
- tests/Notifications/Channels/Discord/DiscordMessageTest.php
Based on issue https://github.com/spatie/laravel-backup/issues/1819.
Reopened pull request from https://github.com/spatie/laravel-backup/pull/1834
@Nielsvanpach This is an initial pull request version. I may need further guidance to ensure it is ready for merging.
> Discord Notifications - Add limits in embed structures in discord notifications messages

- docs/installation-and-setup.md
When I install first time this package I fallowed docs how to install. And after running command `php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"` I got a bunch of unnecessary translation files.
> [DOCS] Update installation-and-setup.md

- src/Config/Config.php
- tests/Config/ConfigTest.php
There is currently a bug on the way the configs are merged. If a "nested array key" is missing on the published config file, `array_merge()` wouldn't add that key and the application will fail to properly boot the config. 
I got the following error after updating from v8 to v9 - ` Undefined array key "compression_method"`.
I dug a bit on it, and indeed my published `backup.php` config file didn't had that key, but that key is present on the package config file: https://github.com/spatie/laravel-backup/blob/fe980cee0a5d2b0773395da3446cd81a3288100a/config/backup.php#L133 so I would expect the "default package value" to be used. 
This PR changes `array_merge` to `array_replace_recursive`, so that we use the package config as the base, and replace any values from the published config file. …
> [BUG] merge published config with package config

- tests/Config/ConfigTest.php
Sorry @freekmurze I forgot to remove the `only()` while writing the tests for PR #1873 .
🙏
> remove the `only()` from tests

- src/Config/NotificationMailSenderConfig.php
Based on issue #1866
Since `NotificationMailSenderConfig::fromArray` is called in `NotificationMailConfig.php` on line 33 : 
```
return new self(
to: $data['to'],
from: NotificationMailSenderConfig::fromArray($data['from'] ?? []),
); 
```
with `$data['from']`, `from` shouldn't be reached again in `NotificationMailSenderConfig` on line 18 and 30 : 
```diff
- $address = $data['from']['address'] ?? config('mail.from.address');
+ $address = $data['address'] ?? config('mail.from.address');
...
- name: $data['from']['name'] ?? config('mail.from.name'),
+ name: $data['name'] ?? config('mail.from.name'),
```
> NotificationMailSenderConfig - remove redundant [ 'from' ] key 

- composer.json
- src/Tasks/Backup/DbDumperFactory.php
- tests/DbDumperFactoryTest.php
The spatie/laravel-backup package currently uses MySQL dumper for all MySQL-compatible databases, including MariaDB.
However, MariaDB has deprecated the mysqldump utility in favor of mariadb-dump as documented in their official documentation.
Recently, a dedicated MariaDB dumper was added to the spatie/db-dumper package in https://github.com/spatie/db-dumper/pull/220, which properly uses the mariadb-dump utility.
This PR updates this package to utilize the new dumper when a MariaDB connection is required.
on-behalf-of: @e-solutions-GmbH <info@esolutions.de>
> Use MariaDb dumper

- src/Tasks/Backup/DbDumperFactory.php
Condition fails for cases when port is valid number, but defined as string as well as checks for range from 1 to 65535.
> Improve port check condition

- tests/DbDumperFactoryTest.php
There is not `getPort` method on `Spatie\DbDumper\DbDumper`
> Fix tests after #1901
