spatie/laravel-backup

composer.json, src/BackupHandlers/Files/FilesBackupHandler.php
Add default back-up of dot files.
=> Can now back-up dot files

src/BackupHandlers/Files/FilesBackupHandler.php
=> Add docblocks

src/Commands/BackupCommand.php
Add an option to only perform a database dump.
=> add only-db option

src/Commands/BackupCommand.php
How did this pass Travis? My PHP7 VM doesn't like it.
=> fixed syntax error

src/BackupHandlers/Database/DatabaseBackupHandler.php, src/BackupHandlers/Database/DatabaseBuilder.php, src/BackupHandlers/Database/Databases/PgSQLDatabase.php, src/Console.php, src/config/laravel-backup.php, tests/PgSQLDatabaseTest.php
Loving your library but I need PostgreSQL support.
Tried to keep this as tidy as possible, please feel free to edit. Its also missing compression support as your library seems to generate a .zip anyway (you can get `pg_dump` to generate a `.tar` file).
Hope this meets the coding standards, I did try my best!
=> PostgreSQL support

src/BackupDestination/Backup.php, src/Commands/BackupCommand.php, src/Commands/CleanupCommand.php, src/Tasks/Backup/BackupJob.php, src/Tasks/Cleanup/CleanupJob.php
- Use consistent punctuation in console output
- '.zip file'
=> Correct console output

config/laravel-backup.php, src/Notifications/Senders/Pushover.php
Send notifications to [Pushover](https://pushover.net/). `PUSHOVER_APP_TOKEN` and `PUSHOVER_USER_KEY` should be set in the `.env` file.
=> Add Pushover sender

src/Tasks/Backup/BackupJob.php, src/Tasks/Backup/FileSelection.php, src/Tasks/Backup/Zip.php, tests/Unit/FileSelectionTest.php
Replaced file arrays with iterators to vastly reduce memory usage and speed up the backup if there are a lot of excluded files.
=> Performance improvements

config/laravel-backup.php
Comment for "allBackups" mentioned "all daily backups".
I kind of fixed those lines 5 minutes before realizing what was wrong ;-)
=> fixes comment

composer.json, config/laravel-backup.php, src/Notifications/Senders/Telegram.php
Add new notification method, using Telegram Bot API on events.
=> Add telegram notification

config/laravel-backup.php
I've only kept the styling of the events config because it looks better to keep it this way.
=> Typo's and formatting

src/Notifications/BaseNotification.php, src/Notifications/Notifications/HealthyBackupWasFound.php, src/Notifications/Notifications/UnhealthyBackupWasFound.php
Here is a pull request that adapts the corrections suggested in issue #274. 
I haven't added any tests. Let me know if you want me to add some tests.
=> fix issues addressed in issue #274

src/Tasks/Backup/FileSelection.php
- Fixed an issue with symlinked folders not honoring exclusions
Fixes #319
=> Symlinks and Exclusions

config/laravel-backup.php
Hi, thank you so much for the awesome project! I just have a quick addition to not use a domain anybody could be listening to, but an official example domain, in case somebody forgets to change this.
Have a great week and a great christmas after that!
=> proper use of example.com domain instead of email.com

src/Tasks/Backup/BackupJob.php, tests/Integration/BackupCommandTest.php
Solves the problem with a default filename not being set.
=> #340 - Filename is not set when zipping.

README.md
Still pointed to v5.0, updated so it redirects to the latest version.
=> Update filesystem documentation link in readme

src/Tasks/Backup/BackupJob.php, tests/Integration/BackupCommandTest.php
=> Changed BackupJob to only exclude the backup destination directory

src/Tasks/Backup/BackupJob.php
=> Update temporary directory to use laravel storage path

src/Tasks/Backup/BackupJob.php
=> Fixing the dump backup on Windows OS

CHANGELOG.md, composer.json, src/Exceptions/CannotCreateDbDumper.php, src/Tasks/Backup/DbDumperFactory.php, tests/Unit/DbDumperFactoryTest.php
=> Add SQLite support

resources/lang/en/notifications.php, src/BackupServiceProvider.php, src/Notifications/BaseNotification.php, src/Notifications/Notifications/BackupHasFailed.php, src/Notifications/Notifications/BackupWasSuccessful.php, src/Notifications/Notifications/CleanupHasFailed.php, src/Notifications/Notifications/CleanupWasSuccessful.php, src/Notifications/Notifications/HealthyBackupWasFound.php, src/Notifications/Notifications/UnhealthyBackupWasFound.php, src/Tasks/Backup/DbDumperFactory.php
This PR contains translations for notifications.
=> Add translations for notifications

src/Tasks/Backup/BackupJobFactory.php
=> Allow backups for app with read/write db hosts in v3 (for <5.3)

src/BackupDestination/BackupDestination.php
=> Fix closing an open file handle

config/laravel-backup.php, src/Notifications/Notifications/BackupHasFailed.php, src/Notifications/Notifications/BackupWasSuccessful.php, src/Notifications/Notifications/CleanupHasFailed.php, src/Notifications/Notifications/CleanupWasSuccessful.php, src/Notifications/Notifications/HealthyBackupWasFound.php, src/Notifications/Notifications/UnhealthyBackupWasFound.php
Add the ability to change the channel of slack notifications.
=> Adding ability to change the slack channel

resources/lang/fr/notifications.php
Hi there, thanks for that awesome package! 👏
=> Add French translations

resources/lang/da/notifications.php
I've translated the notification messages to Danish.
=> Add Danish translation

src/Commands/BackupCommand.php, src/Commands/CleanupCommand.php, src/Tasks/Backup/BackupJob.php, src/Tasks/Cleanup/CleanupJob.php, tests/Integration/BackupCommandTest.php, tests/Integration/CleanupCommandTest.php
add the `--no-notifications` flag as mentioned in #461
=> add no-notifications flag for backup:run command, fixes #461

resources/lang/es/notifications.php
Hey guys. I had to translate the notifications to Spanish for a project, so I want to contribute with this, maybe it will be helpful to someone else.
=> Spanish notifications

src/Tasks/Backup/DbDumperFactory.php, tests/Unit/DbDumperFactoryTest.php
=> Merge all the read connection parameters when setting the database configuration

resources/lang/it/notifications.php
Here is the Italian translation.
Thanks for the great package!!
=> Added Italian translations

config/backup.php
Solution as per https://github.com/spatie/laravel-backup/issues/568#issuecomment-344587943. Thanks!
=> Use config instead of env. Fix #568

src/Events/HealthyBackupWasFound.php, src/Events/UnhealthyBackupWasFound.php, src/Helpers/ConsoleOutput.php, src/Tasks/Cleanup/CleanupJob.php, tests/TestHelper.php
After running [`PHPStan`](https://github.com/phpstan/phpstan) up to level 2, some code could be refactored :smile:
=> Fixes from PHPStan

src/Tasks/Backup/DbDumperFactory.php, tests/Unit/DbDumperFactoryTest.php
Adresses https://github.com/spatie/laravel-backup/issues/587.
=> Update DbDumperFactory to handle an array of DB hosts

resources/lang/id/notifications.php
This is translation for Bahasa or Indonesian Language.
thanks before.
=> Added indonesian translation

src/Exceptions/InvalidBackupJob.php, tests/Integration/BackupCommandTest.php
=> fix typo in InvalidBackupJob exception

resources/lang/tr/notifications.php
=> Add turkish translation

resources/lang/hi/notifications.php
=> Hindi translation

src/Tasks/Backup/BackupJob.php
=> Fix wrong import from #622 fixes #663

config/backup.php, src/Tasks/Backup/BackupJob.php
=> Setting a temporary directory through the config file

composer.json
=> Fixed copy/paste mistake

.travis.yml
=> add support test for php 7.3

tests/Integration/CleanupCommandTest.php
This pull request adds an accompanying test for the fix to issue #776 😃
=> Add cleanup command used storage display test

composer.json
This pull request revert the dependency schema to make it lumen compatible.
=> fix lumen compatibility for dependency schema

config/backup.php
=> Adds a default value for APP_NAME.

src/Notifications/BaseNotification.php
I realise this is a bonkers tiny nitpick... I get to see this notification multiple times per day and it always bugs me just a little bit.
=> Change amount to number

composer.json
For those of us who still work on PHP 7.1.* but want to use Laravel 5.8 :)
=> Add support for Laravel 5.8

src/Tasks/Backup/BackupJob.php, src/Tasks/Backup/FileSelection.php, src/Tasks/Backup/Zip.php, tests/FileSelectionTest.php
Fixes #859 with empty directories not being backed up
=> Empty directories are now being backed up

resources/lang/fi/notifications.php
Add resources/lang/fi/notifications.php
=> Add Finnish localization

src/Tasks/Backup/DbDumperFactory.php
=> add unix_socket

resources/lang/ja/notifications.php
Hi, Spatie.
Thank you for great packages for us.
I added Japanese localization to `laravel-backup`.
Could you please merge into the original package.
=> Added Japanese localization

docs/installation-and-setup.md
@freekmurze please review if this wording is acceptable. refers to https://github.com/spatie/laravel-backup/pull/1136
=> add a note about default backup destination to installation-and-setup.md

src/BackupDestination/Backup.php
I added an extra test to check if the filesystem has deleted the backup.
This fixes #1108.
=> Test backup deletion

src/Events/BackupHasFailed.php, src/Events/CleanupHasFailed.php, src/Notifications/EventHandler.php, src/Tasks/Monitor/HealthChecks/MaximumStorageInMegabytes.php
This PR adds missing visibility keywords to promoted properties.
=> Add missing visibility keyword

docs/installation-and-setup.md
It's really not that important, but it could make a difference for someone (given your large user base), so I decided to suggest it. No explanation needed, nor bad feelings, if you decide just to discard it :-)
=> Small improvement suggestion for the backup times

src/BackupDestination/BackupDestination.php
Already merged on master but useful for php 7.4 users that are still using laravel-backup 6.x
=> Fix for #1225

docs/advanced-usage/encrypt-backup-archives.md
port of #1249 
discussed in #1246
=> add note on how to restore and macos

docs/advanced-usage/encrypt-backup-archives.md
=> add note how to restore and macos

docs/installation-and-setup.md
Hey friends!
I love this package and can't believe I've only just found it! Looks like I'll be owing another postcard :wink: 
In the meantime, here's a small PR to fix a minor spelling mistake and tweak the wording a little.
All the best.
=> Fix spelling and tweak wording

CHANGELOG.md, config/backup.php, src/Listeners/EncryptBackupArchive.php
Apply changes of version 7 to version 6 of this package
=> fix: zip module undefined constant in config #1254 fo version 6

src/Events/DumpingDatabase.php, src/Tasks/Backup/BackupJob.php, tests/Events/DumpingDatabaseTest.php
=> Add DumpingDatabase event v6

resources/lang/ja/notifications.php
Hi @freekmurze,
I found a translation error and corrected it.
=> Fix: translation of "date"

resources/lang/bn/notifications.php
- Updated Bengali Translations
=> Updated Bengali Transitions

src/Tasks/Backup/Zip.php, tests/Commands/BackupCommandTest.php, tests/TestCase.php
=> Avoid create full path folders when config has relative_path

src/Tasks/Backup/FileSelection.php
=> [V6] Fix directory separator for windows

src/Tasks/Backup/FileSelection.php
=> [v6] Fix undefined constant GLOB_BRACE on alpine

tests/Commands/BackupCommandTest.php, tests/TestCase.php
Test for avoid questions like #1413, https://github.com/spatie/laravel-backup/discussions/1377#discussioncomment-1207602, and avoid break this again
=> [V6] Test for avoid full path on db file

CHANGELOG.md, src/Exceptions/InvalidBackupDestination.php, src/Tasks/Backup/BackupJob.php, src/Tasks/Backup/FileSelection.php, tests/Commands/BackupCommandTest.php, tests/FileSelectionTest.php, tests/TestCase.php, tests/stubs/.dot/file1.txt, tests/stubs/file, tests/stubs/file1.txt.txt
=> Upgrade v7 with v6 working changes

resources/lang/nl/notifications.php
newest_backup_date and oldest_backup_date were not translated.
=> Fixed translated strings in Dutch

src/Tasks/Backup/BackupJob.php, tests/Commands/BackupCommandTest.php
I have added a test which fails without the changes made in the subsequent commit.
Fixes #1485
=> Fix issue where local backups were included in new backups

src/Tasks/Backup/BackupJob.php
close https://github.com/spatie/laravel-backup/issues/1468
=> Check if backup destination is reachable before trying to copy backup

resources/lang/pt-BR/notifications.php
Wrong translations in three keys
=> Fixes Brazilian Translation

resources/lang/cs/notifications.php
I changed some bad translations and typos.
Additionally - duplication on lines 40 and 43 caused emails not to have line with backup size (since the collection is filtered)
=> Fix mistakes in cs/notifications.php

src/BackupDestination/BackupDestination.php
This allows navigating subfolders with "/"
...as discussed in https://github.com/spatie/laravel-backup/discussions/1497
=> Allow any characters in backup destination name

.github/workflows/run-tests.yml, composer.json, tests/BackupDestination/BackupCollectionTest.php, tests/BackupDestination/BackupTest.php, tests/Commands/BackupCommandTest.php, tests/Commands/CleanupCommandTest.php, tests/Commands/ListCommandTest.php, tests/DbDumperFactoryTest.php, tests/Events/BackupHasFailedTest.php, tests/Events/BackupManifestWasCreatedTest.php, tests/Events/BackupWasSuccessfulTest.php, tests/Events/BackupZipWasCreatedTest.php, tests/Events/CleanupHasFailedTest.php, tests/Events/CleanupWasSuccessfulTest.php, tests/Events/DumpingDatabaseTest.php, tests/Events/UnhealthyBackupWasFoundTest.php, tests/FileSelectionTest.php, tests/FormatTest.php, tests/HealthChecks/IsReachableTest.php, tests/HealthChecks/MaximumAgeInDaysTest.php, tests/HealthChecks/MaximumStorageInMegabytesTest.php, tests/Listeners/EncryptBackupArchiveTest.php, tests/ManifestTest.php, tests/Notifications/EventHandlerTest.php, tests/Pest.php, tests/TestCase.php, tests/TestSupport/FakeFailingHealthCheck.php, tests/ZipTest.php
This pull request contains changes for migrating your test suite from PHPUnit to [Pest](https://pestphp.com/) automated by the [Pest Converter](https://laravelshift.com/phpunit-to-pest-converter).
**Before merging**, you need to:
- Checkout the `shift-57947` branch
- Review **all** of the comments below for additional changes
- Run `composer update` to install Pest with your dependencies
- Run `vendor/bin/pest` to verify the conversion
=> PHPUnit to Pest Converter

docs/installation-and-setup.md
Used current source of https://github.com/spatie/laravel-backup/blob/main/config/backup.php
=> docs(setup): update default config

resources/lang/it/notifications.php
This PR fix two wrong Italian translations used on notifications.
=> Italian translations

docs/installation-and-setup.md
By default, backup isn't in public folder
=> Fix error an Installation Doc

resources/lang/zh-TW/notifications.php
disk -> 磁碟
------
If PR is accepted and you don't mind, could you add a `hacktoberfest-accepted` label to help me with hacktoberfest? Thanks!
=> fix: zh-TW translation

README.md
This PR removes the "Support Ukraine" banner from the README.
_id:update-readme-banner/v1.0_
=> Update Readme Banner

src/Tasks/Backup/Zip.php, tests/Commands/BackupCommandTest.php
https://github.com/spatie/laravel-backup/pull/1683#issuecomment-1671017968
This problem should be solved
=> Fix: relative_path too short, example: /app

resources/lang/pt-BR/notifications.php, resources/lang/pt/notifications.php
Hello, simple PR to add missing translations.
Regards,
Helder
=> Added missing PT and PT/BR translations

config/backup.php
This PR replaces the docblocks with comments in the configuration file.
=> Docblocks to comments

docs/installation-and-setup.md
Fix the monitoring documentation link in the installation page.
=> Fix broken link in installation-and-setup.md

resources/lang/sk/notifications.php
This PR adds `Slovak` language.
=> feat: add `Slovak` language

src/BackupServiceProvider.php, tests/Config/ConfigTest.php
Fix #1871 this bug was created by #1846
=> Fix temp directory config path and add unit test

resources/lang/kk/notifications.php
Added kk/notification.php file
=> Kazakh language support 🇰🇿
